version: "3.8"
volumes:
  data:

services:
  auth:
    build: ./auth
    container_name: auth-micro
    ports:
      - "8000:8000"
    networks:
      - SOA
  storage:
    build: ./storage
    container_name: storage-micro
    ports:
      - "8001:8000"
    networks:
      - SOA
  employee:
    build: ./employee
    container_name: employee-micro
    ports:
      - "8002:8000"
    networks:
      - SOA
  authdb:
    image: postgres:latest
    container_name: authpg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    networks:
      - SOA
  storagedb:
    image: postgres:latest
    container_name: storagepg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: storage
    ports:
      - "5433:5432"
    networks:
      - SOA
  employeedb:
    image: postgres:latest
    container_name: employeepg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: employee
    ports:
      - "5434:5432"
    networks:
      - SOA

networks:
  SOA:
