version: "3.8"
volumes:
  data:

services:
  authdb:
    image: postgres:latest
    container_name: authdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    networks:
      - SOA

networks:
  SOA:
